### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by Ps2Fino** [carloratm/peliconf#2]
Hi

I'm trying to get the nav bar to show.
I figured out from reading the source code how to get pages to show up by creating a list of JSON objects in the pelicanconf.py configuration file like:

PAGES = (
  {},
  ...
)

However, I can't figure out how to get the SCHEDULE variable to fill into my schedule.rst file (which generates to schedule.html).
Any help would be greatly appreciated; I'd really like to use this template as its awesome!

**Comment by carloratm** [comment]
The SCHEDULE variable is defined in  pelicanconf.py, for an example, see:

https://github.com/carloratm/peliconf/blob/master/peliconf-example-conf.py#L108

It is a quite complex structure, I hope the example can help you get the result you need.

**Comment by Ps2Fino** [comment]
Thanks for the reply.
I found the SCHEDULE structure, my problem is getting it to generate inside schedule.html

In the base.html template on line 62, I could get the CSS to generate when I removed the if statement to test it working.
However, I don't know how to specify the 'page' variable in the 'if p == page' statement.

Do you have the source for the theme demo hosted on http://peliconf.carlorat.me that I could look at please?

**Comment by carloratm** [comment]
Yes, the demo site project is at: https://gitlab.com/carlo.ratm/peliconf-demo-site/tree/master
In particular, the schedule page source is: https://gitlab.com/carlo.ratm/peliconf-demo-site/raw/master/content/pages/schedule.rst

**Comment by Ps2Fino** [comment]
Awesome, thank you!
I should be able to figure out my problem by reading your source code :-)
